name: Actions
on:
    push:
        branches: [main]
jobs:
    testing-actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Run Hello Action
              uses: ./.github/actions/hello
              id: hello
              with:
                  who-to-greet: "World"
            - run: |
                  echo "Time: ${{ steps.hello.outputs.time }}"
