name: Actions
on: push

jobs:
    testing-actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Send a Slack Message
              uses: ./.github/actions/slack
              with:
                slack_webhook: ${{ secrets.SLACK_WEBHOOK }}
                message: Hello Slack
            #- name: Run Issue Action
            #uses: ./.github/actions/issue
            #id: issue
            #with:
            #    token: ${{ secrets.GIT_TOKEN }}
            #    title: A New Issue
            #    body: New Issue Body
            #    assignees: |
            #        jthomason22
            #- run: |
            #      echo $ {{ steps.issue.outputs.issue }}
            - name: Run Hello Action
              uses: ./.github/actions/hello-docker
              id: hello
              with:
                  who-to-greet: "World!"
            - name: Get Time
              run: |
                  echo "Time: ${{ steps.hello.outputs.time }}"
                  echo $HELLO
            - name: Run prebuilt Hello World
              uses: actions/hello-world-javascript-action@v1.1
              with:
                  who-to-greet: "Mona the Octocat"