name: Actions
on: push

jobs:
    testing-actions:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Run Hello Action
              uses: ./.github/actions/hello
              id: hello
              with:
                  who-to-greet: "World!"
            - name: Get Time
              run: |
                  echo "Time: ${{ steps.hello.outputs.time }}"
            - name: Run prebuilt Hello World
              uses: actions/hello-world-javascript-action@v1.1
              with:
                  who-to-greet: "Mona the Octocat"
