name: Open Github Issue
author: John Thomason
description: Some description
inputs:
  token:
    description: 'Github Token'
    required: true
  title:
    description: 'Issue Title'
    required: true
  body:
    description: 'Issue Body'
    required: false
  assignees:
    description: 'Issue Assignees'
    required: false
outputs:
  issue: #id of ouput
    description: 'The issue object as a json string'
runs:
  using: 'node16'
  main: 'dist/index.js'





